version: '3.8'
services:
  mymessageq-db-2:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=sa
      - MYSQL_ROOT_PASSWORD=helloworld
      - MYSQL_DATABASE=mymessageq
    ports:
      - '3307:3306'
    volumes:
      - mysql-messageq-db:/var/lib/mysql
volumes:
  mysql-messageq-db:
    driver: local