version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mymessageq
    ports:
      - '5440:5432'
    volumes:
      - mymessageq-db:/var/lib/postgresql/data
volumes:
  mymessageq-db:
    driver: local